# Generated by Django 5.2.15 on 2026-07-15 23:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.CharField(max_length=300)),
                ('content', models.TextField(help_text='One paragraph per line')),
                ('image', models.ImageField(upload_to='blog/')),
                ('category', models.CharField(max_length=100)),
                ('read_time', models.CharField(default='5 min read', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
