# Generated by Django 5.2.15 on 2026-08-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Shown in the storefront's featured products section."),
        ),
    ]
